# Title: playbook.yml
# Date: 07/09/2017
# Author: Tom Gillot
# Purpose: Ubuntu Server LTS 16.04.2 Q3 host setup using Ansible
# Version 0.2.0
# License:
#   playbook.yml Provision an Ubuntu Server LTS 16.04.2 machine
#   Copyright (C) 2017  Tom Gillot
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
#

---
- name: Q3 Ubuntu 16.04.2 setup
  hosts: default
  tasks:
  # Make sure the ansible.cnf file exists and set to prompt for sudo
  # password -- vagrant in this case.
  - name: Print message
    debug: msg="Beginning of Ubuntu 16.04.2 configuration Ansible script."

  - name: Print Lab 2 Setup
    debug: msg="Provisioning Q3 Ubuntu Host"
    
  - name: Create admin user
    shell: useradd -c "Q3 admin" -G admin q3admin
    become: true
    become_method: sudo
    become_user: root

  - name: Create admin home dir
    file:
      path: /home/q3admin
      state: directory
      owner: q3admin
      group: q3admin
      mode: 0755
    become: true
    become_method: sudo
    become_user: root
    
  - name: Create admin ssh dir
    file:
      path: /home/q3admin/.ssh
      state: directory
      owner: q3admin
      group: q3admin
      mode: 0700
    become: true
    become_method: sudo
    become_user: root

  - name: Creates admin authorized_keys dir
    file:
      path: /home/q3admin/.ssh/authorized_keys
      state: directory
      owner: q3admin
      group: q3admin
      mode: 0644
    become: true
    become_method: sudo
    become_user: root
    
  - name: Copy pubilic key to admin authorized_keys dir
    copy:
      src: authorized_keys
      dest: /home/q3admin/.ssh/authorized_keys
      owner: q3admin
      group: q3admin
      mode: 0600
    become: true
    become_method: sudo
    become_user: root
    
  - name: Disable sudo password for admin group
    shell: sed -i 's/%admin ALL=(ALL) ALL/%admin ALL=(ALL) NOPASSWD':' ALL/g' /etc/sudoers
    become: true
    become_method: sudo
    become_user: root
    
  - name: update apt packages
    become: true
    become_method: sudo
    become_user: root
    apt:
      update_cache: yes
      
  - name: Install Aptitude
    apt:
      name:  aptitude
      state: present
    become: true
    become_method: sudo
    become_user: root
    
  - name: Install Puppet
    apt:
      name:  puppet
      state: present
    become: true
    become_method: sudo
    become_user: root
    
  - name: Install Puppermaster
    apt:
      name: puppetmaster
      state: present
    become: true
    become_method: sudo
    become_user: root
    
  - name: Install Facter
    apt:
      name: facter
      state: present
    become: true
    become_method: sudo
    become_user: root

  - name: Print Lab 3 Setup
    debug: msg="Remove old Docker packages and install Docker"
  
  - name: Remove 'docker-engine'
    apt: 
      name: docker-engine
      state: absent
    become: true
    become_method: sudo
    become_user: root
  
  - name: Remove 'docker-ce'
    apt: 
      name: docker-ce
      state: absent
    become: true
    become_method: sudo
    become_user: root
    
  - name: Remove 'docker.io'
    apt: 
      name: docker.io
      state: absent
    become: true
    become_method: sudo
    become_user: root
    
  - name: update apt packages
    become: true
    become_method: sudo
    become_user: root
    apt:
      update_cache: yes
    
  - name: Install packages to to allow apt to use repo over HTTPS
    action: apt pkg={{item}} state=present
    with_items: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    become: true
    become_method: sudo
    become_user: root
  
  - name: Add Docker official DPG key
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true
    become_method: sudo
    become_user: root
  
  - name: Add stable Docker repository
    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    become: true
    become_method: sudo
    become_user: root
  
  - name: update apt packages
    become: true
    become_method: sudo
    become_user: root
    apt:
      update_cache: yes
    
  - name: Install 'docker-ce'
    apt: 
      name: docker-ce
      state: present
    become: true
    become_method: sudo
    become_user: root
